### ISSUE TITLE
Instruction failed: `syndicate-touch` 

### ISSUE THREAD

**Issue by ChunKunWang** [syndicate-storage/syndicate-core#17]
The `syndicate-touch` instruction doesn't work.  The drivers I used for RG and AG container:  `./syndicate-fs-driver/src/sgfsdriver/ag_driver` for AG container, and `./syndicate-core/python/syndicate/rg/drivers/disk` for RG container.   The detail error message is as follows.

[log-touch.txt](https://github.com/syndicate-storage/syndicate-core/files/605017/log-touch.txt)

**Comment by iychoi** [comment]
Would you check the MS's database for RG's gateway id? It seems that UG tried to connect to AG for some reasons but failed. This may be because MS returned AG's gateway ID instead of RG's.
Your log says the `/irods-file.txt` already exists at a coordinator (gateway) `5062879461503535207`. This must be RG's ID because you are creating a file. If it's AG's ID, it means AG already published the same file before in read-only. Thus, you can't overwrite the same path via RG.

**Comment by ChunKunWang** [comment]
I agree with you.  I conduct another experiment to test whether `syndicate-touch` is able to create files that don't exist yet in the MS.  The result shows that `syndicate-touch` is failed to touch `DATA X-Update-Times` of /irods-file.txt which already exists but succeed to update and create the `DATA X-Update-Times` of files that are uploaded from UG.  Thanks for your help.
